name: Build Docker

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/386, linux/arm/v6, linux/arm/v7, linux/arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Run Buildx
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --output "type=image,push=false" \
            --cache-to=type=local,dest=docker-cache/${{ matrix.platform }} ./

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: docker-cache
          path: docker-cache

  deploy_dev:
    name: Deploy Dev
    if: startsWith(github.ref, 'refs/heads/') # Just the branches
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment
        run: |
          echo "::set-env name=DOCKER_REPO::dungeonrevealer/dungeon-revealer"

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - uses: actions/download-artifact@v1
        with:
          name: docker-cache
          path: docker-cache

      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            -t $DOCKER_REPO:dev \
            --cache-from=type=local,src=docker-cache/linux/amd64 \
            --cache-from=type=local,src=docker-cache/linux/386 \
            --cache-from=type=local,src=docker-cache/linux/arm/v6 \
            --cache-from=type=local,src=docker-cache/linux/arm/v7 \
            --cache-from=type=local,src=docker-cache/linux/arm64 ./


  deploy_release:
    name: Deploy release
    if: startsWith(github.ref, 'refs/tags/') # Just the tags
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment
        run: |
          export TAG="${GITHUB_REF#'refs/tags/'}"
          echo "::set-env name=GH_TAG::$TAG"
          echo "::set-env name=DOCKER_REPO::dungeonrevealer/dungeon-revealer"

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - uses: actions/download-artifact@v1
        with:
          name: docker-cache
          path: docker-cache

      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/386 \
            --output "type=image,push=true" \
            -t $DOCKER_REPO:release \
            -t $DOCKER_REPO:$GH_TAG \
            -t $DOCKER_REPO:stable \
            -t $DOCKER_REPO:latest \
            --cache-from=type=local,src=docker-cache/linux/amd64 \
            --cache-from=type=local,src=docker-cache/linux/386 \
            --cache-from=type=local,src=docker-cache/linux/arm/v6 \
            --cache-from=type=local,src=docker-cache/linux/arm/v7 \
            --cache-from=type=local,src=docker-cache/linux/arm64 ./

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: $DOCKER_REPO
          README_FILEPATH: README.md
